site_name: SheetShuttle API Documentation
site url: https://SheetShuttle.github.io
nav:
    - Home: index.md
    - Google API Setup: Google_API_Setup.md
    - Getting Started: Getting_Started.md
    - Schemas: Schemas.md
    - Tutorial: Tutorial.md


theme:
    name: mkdocs
    nav_style: dark 
    palette:
      primary: green

