site_name: team4_pkg
site url: https://SheetShuttle.github.io
nav:
    - Home: index.md
    - Google_API_Setup: Google_API_Setup.md
    - Getting_Started: Getting_Started.md
    - Schemas: Schemas.md
    - Tutorial: tutorial.md


theme:
  name: null
  custom_dir: 'mkdocs_docskimmer'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
    version: 0.3.x



