# ID of the sheet to be retrieved
# TODO: define a schema for this structure
source_id: 1ZUHnR_KjCji7PEnzAIorVx_Ta-I19WWLcjT1B3fzNzQ
# sheets must be literal key
sheets:
    - name: sheet1
      regions:
        - name: names
          start: A1
          end: B2
          contains_headers: true
        - name: labs
          start: C1
          end: E2
          contains_headers: true
        - name: practicals
          start: F1
          end: H2
          contains_headers: true
        - name: random
          start: D11
          end: F13
          contains_headers: false
          headers:
            - assignment1
            - assignment2
            - assignment3
