# ID of the sheet to be retrieved
# TODO: define a schema for this structure
source_id: 1pZqI5VJMmg4w4upGKLu2C6Etl7qvSXXCnUTuoa_6U-o
# path where output will be saved as csv file
output_path: output/lab1
# sheets must be literal key
sheets:
    - name: "1"
      start: A1
      end: C3
      columns:
        - Name
        - Class
    - name: "2"
      start: A1
      end: B3
      columns:
        - Name
        - Room
