# this format supports the following
# creating new issues
# commenting on existing issues
# Adding new files
# Updating existing files
- type: issue
  status: new
  repo: AC-GopherBot/test-1
  title: This is a very new issue
  body: "|    |   assignment1 |   assignment2 |   assignment3 |
|---:|--------------:|--------------:|--------------:|
|  0 |             4 |             6 |          1234 |
|  1 |            87 |            45 |           357 |
|  2 |           132 |          1234 |         43327 |"
